### ISSUE TITLE
Prefer to use the config basename as the actual inner config name.

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#52]
As discussed with @doug-walker and @carolalynn22, we currently use a human readable inner config name:

```yaml
ocio_profile_version: 2.1

environment:
  {}
search_path: ""
strictparsing: true
luma: [0.2126, 0.7152, 0.0722]
name: Academy Color Encoding System - CG Config [COLORSPACES v0.1.0] [ACES v1.3] [OCIO v2.1.1]
description: |
  The "Academy Color Encoding System" (ACES v1.3) "CG Config"
  -----------------------------------------------------------
  
  This minimalistic "OpenColorIO" config is geared toward computer graphics artists requiring a lean config that does not include camera colorspaces and the less common displays and looks.
  
  Generated with "OpenColorIO-Config-ACES" v0.1.1-14-gec7d1cf on the 2022/05/10 at 20:12.
```

i.e. `Academy Color Encoding System - CG Config [COLORSPACES v0.1.0] [ACES v1.3] [OCIO v2.1.1]`

It would be desirable to line it up with the actual config basename for pipeline purposes, i.e. `cg-config-v0.1.0_aces-v1.3_ocio-v2.1.1`.ocio.

We could then change the description title to use the current inner config name:

```yaml
ocio_profile_version: 2.1

environment:
  {}
search_path: ""
strictparsing: true
luma: [0.2126, 0.7152, 0.0722]
name: cg-config-v0.1.0_aces-v1.3_ocio-v2.1.1
description: |
  Academy Color Encoding System - CG Config [COLORSPACES v0.1.0] [ACES v1.3] [OCIO v2.1.1]
  ----------------------------------------------------------------------------------------
  
  This minimalistic "OpenColorIO" config is geared toward computer graphics artists requiring a lean config that does not include camera colorspaces and the less common displays and looks.
  
  Generated with "OpenColorIO-Config-ACES" v0.1.1-14-gec7d1cf on the 2022/05/10 at 20:12.
```
