### ISSUE TITLE
Not all config files work in UE 4.27.2

### ISSUE THREAD

**Issue by RSN4D** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#83]
this is related to .rc2

some of the config file give error "invalid configuration file" when making ocio asset in UE 4.27.2.

for example:
studio-config-v1.0.0-rc2_aces-v1.3_ocio-v2.0.ocio
is working in ue 4.27.2

studio-config-v1.0.0-rc2_aces-v1.3_ocio-v2.1.ocio
is not working in ue 4.27.2

also, what to use for Unreal engine input transform?
shouldn't there be a: input: linear-sRGB?

**Comment by KelSolaar** [comment]
Hello @RSN4D,

I'm actually surprised that any config work at all with UE 4.27.2 as it ships with OCIO 1.1.0: https://github.com/EpicGames/UnrealEngine/blob/d94b38ae3446da52224bedd2568c078f828b4039/Engine/Plugins/Compositing/OpenColorIO/Source/ThirdParty/OpenColorIO/distribution/include/OpenColorIO/OpenColorABI.h#L35

As for `Utility - Linear - sRGB`, whenever possible, we have aliased the old colorspaces:

```yaml
- !<ColorSpace>
    name: Linear Rec.709 (sRGB)
    aliases: [lin_rec709_srgb, Utility - Linear - Rec.709, lin_rec709, lin_srgb, Utility - Linear - sRGB]
    family: Utility
    equalitygroup: ""
    bitdepth: 32f
    description: |
      Convert ACES2065-1 to linear Rec.709 primaries, D65 white point
      
      CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Linear_Rec709:1.0
    isdata: false
    categories: [file-io, working-space]
    encoding: scene-linear
    allocation: uniform
    from_scene_reference: !<GroupTransform>
      name: AP0 to Linear Rec.709 (sRGB)
      children:
        - !<MatrixTransform> {matrix: [2.52168618674388, -1.13413098823972, -0.387555198504164, 0, -0.276479914229922, 1.37271908766826, -0.096239173438334, 0, -0.0153780649660342, -0.152975335867399, 1.16835340083343, 0, 0, 0, 0, 1]}
```
