### ISSUE TITLE
Adding P3-D65 (aka DisplayP3) gamut support

### ISSUE THREAD

**Issue by hpd** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#97]
**Problem Statement**
Many devices used in the ACES, OCIO and USD ecosystems for content authoring and display have screens that use the P3 primaries and D65 white point. In the Apple ecosystem, this gamut is generally referred to as "Display P3". Thus far, the ACES OCIO config has colorspaces designed to support textures authored with either the sRGB gamut or the ACES AP1 (aka ACEScg) gamut, with a couple of different transfer functions. It also has a colorspace for handling linear content with the P3-D65 gamut. It has not had colorspaces that support textures authored with the P3 primaries, D65 white point and sRGB transfer function.

As such, it would be5 valuable to the community of users of the ACES OCIO config to add colorspaces that directly support textures authored with the P3-D65 (aka DisplayP3) gamut.

**Proposed solution**
Add colorspaces the support the following combination of primaries, white points and transfer functions

- P3 primaries, D65 white point, sRGB transfer function

The colorspaces would be named

- sRGB encoded - P3-D65 - Texture

In order to provide the most flexibility to different pipelines and authoring ecosystems, these colorspaces would have the following aliases

- srgb_p3d65
- srgb_encoded_p3d65_tx
- srgb_displayp3

As a related, but somewhat separate issue, the proposal would put these colorspaces in the following family:
Input/Texture
Given that that may end up being a separate Issue, the colorspaces would live in the Utility family.

These colorspaces would be in the following category
texture

**Comment by doug-walker** [comment]
The aliases look good.  For consistency with the other spaces, I think we should remove the first dash from the name and use a capital E, as follows:
name: "sRGB Encoded P3-D65 - Texture"

I will take an action item to add the color space to the built-in transforms in the OCIO library.

**Comment by KelSolaar** [comment]
@doug-walker : I started to work on that in #100.

**Comment by doug-walker** [comment]
At the Configs WG meeting we discussed also adding a display color space for Display P3.  I took the action item to summarize all of the changes proposed for the next configs release.

For the CG config:
```
displays:
  Display P3 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [ACES 1.0 - SDR Video, Un-tone-mapped]
```

For the Studio config:
```
displays:
  Display P3 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [ACES 1.0 - SDR Video, ACES 1.0 - SDR Video (D60 sim on D65), Un-tone-mapped]
```

For both configs:
```
display_colorspaces:
  - !<ColorSpace>
    name: Display P3 - Display
    aliases: [displayp3_display]
    family: Display
    categories: [file-io]
    encoding: sdr-video

colorspaces:
  - !<ColorSpace>
    name: sRGB Encoded P3-D65 - Texture
    aliases: [srgb_p3d65, srgb_encoded_p3d65_tx, srgb_displayp3]
    family: Utility
    categories: [file-io, texture]
    encoding: sdr-video
```

For both configs, updates to aliases and categories:
```
  - !<ColorSpace>
    name: Linear P3-D65
    aliases: [lin_p3d65, Utility - Linear - P3-D65, lin_displayp3, Linear Display P3]
    family: Utility
    categories: [file-io, working-space, texture]
    encoding: scene-linear
```

And in addition we should add the texture category to additional color spaces in the CG and Studio configs.  I will create a separate issue for that.
